-- Permission persistence foundation for PostgreSQL.
-- UUIDs are generated by PostgreSQL's built-in gen_random_uuid().

CREATE TYPE "PermissionPrincipalType" AS ENUM ('discord-user', 'discord-role');
CREATE TYPE "PermissionScopeType" AS ENUM ('platform', 'discord-guild');
CREATE TYPE "PermissionAssignmentEffect" AS ENUM ('allow', 'deny');
CREATE TYPE "PermissionAuditAction" AS ENUM ('set-assignment', 'revoke-assignment');
CREATE TYPE "PermissionMutationReasonCode" AS ENUM ('bootstrap', 'administrator-action', 'security-response', 'role-synchronization', 'migration', 'expiration', 'system-maintenance');
CREATE TYPE "PermissionAuditActorType" AS ENUM ('principal', 'system');

CREATE TABLE "guilds" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "discord_guild_id" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "disabled_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    CONSTRAINT "guilds_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "guilds_enabled_state_check" CHECK (("enabled" AND "disabled_at" IS NULL) OR (NOT "enabled" AND "disabled_at" IS NOT NULL))
);

CREATE TABLE "permission_principals" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "type" "PermissionPrincipalType" NOT NULL,
    "guild_id" UUID NOT NULL,
    "external_id" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "disabled_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    CONSTRAINT "permission_principals_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "permission_principals_external_id_check" CHECK (length(btrim("external_id")) > 0),
    CONSTRAINT "permission_principals_enabled_state_check" CHECK (("enabled" AND "disabled_at" IS NULL) OR (NOT "enabled" AND "disabled_at" IS NOT NULL))
);

CREATE TABLE "permission_definitions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "key" TEXT NOT NULL,
    "description" TEXT,
    "category" TEXT,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "disabled_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    CONSTRAINT "permission_definitions_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "permission_definitions_key_format_check" CHECK ("key" ~ '^[a-z][a-z0-9]*(\.[a-z][a-z0-9]*)+$'),
    CONSTRAINT "permission_definitions_enabled_state_check" CHECK (("enabled" AND "disabled_at" IS NULL) OR (NOT "enabled" AND "disabled_at" IS NOT NULL))
);

CREATE TABLE "permission_assignments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "principal_id" UUID NOT NULL,
    "permission_definition_id" UUID NOT NULL,
    "scope" "PermissionScopeType" NOT NULL,
    "guild_id" UUID,
    "effect" "PermissionAssignmentEffect" NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "expires_at" TIMESTAMPTZ(3),
    "revoked_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    CONSTRAINT "permission_assignments_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "permission_assignments_scope_guild_check" CHECK (("scope" = 'platform' AND "guild_id" IS NULL) OR ("scope" = 'discord-guild' AND "guild_id" IS NOT NULL)),
    CONSTRAINT "permission_assignments_expiration_check" CHECK ("expires_at" IS NULL OR "expires_at" > "created_at"),
    CONSTRAINT "permission_assignments_revocation_check" CHECK (("enabled" AND "revoked_at" IS NULL) OR (NOT "enabled" AND "revoked_at" IS NOT NULL AND "revoked_at" >= "created_at"))
);

CREATE TABLE "permission_audit_events" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "action" "PermissionAuditAction" NOT NULL,
    "actor_type" "PermissionAuditActorType" NOT NULL,
    "actor_principal_id" UUID,
    "actor_principal_type" "PermissionPrincipalType",
    "actor_external_id" TEXT,
    "actor_guild_discord_id" TEXT,
    "actor_service" TEXT,
    "target_principal_id" UUID,
    "target_principal_type" "PermissionPrincipalType",
    "target_external_id" TEXT,
    "target_guild_discord_id" TEXT,
    "scope" "PermissionScopeType",
    "scope_guild_id" UUID,
    "scope_guild_discord_id" TEXT,
    "permission_definition_id" UUID,
    "permission_key" TEXT,
    "assignment_id" UUID,
    "reason_code" "PermissionMutationReasonCode" NOT NULL,
    "reason" TEXT,
    "correlation_id" UUID NOT NULL,
    "before_snapshot" JSONB,
    "after_snapshot" JSONB,
    "occurred_at" TIMESTAMPTZ(3) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "permission_audit_events_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "permission_audit_events_actor_check" CHECK (("actor_type" = 'principal' AND "actor_principal_id" IS NOT NULL AND "actor_principal_type" IS NOT NULL AND "actor_external_id" IS NOT NULL AND "actor_guild_discord_id" IS NOT NULL AND "actor_service" IS NULL) OR ("actor_type" = 'system' AND "actor_principal_id" IS NULL AND "actor_principal_type" IS NULL AND "actor_external_id" IS NULL AND "actor_guild_discord_id" IS NULL AND length(btrim("actor_service")) > 0)),
    CONSTRAINT "permission_audit_events_target_check" CHECK (("target_principal_id" IS NULL AND "target_principal_type" IS NULL AND "target_external_id" IS NULL AND "target_guild_discord_id" IS NULL) OR ("target_principal_id" IS NOT NULL AND "target_principal_type" IS NOT NULL AND "target_external_id" IS NOT NULL AND "target_guild_discord_id" IS NOT NULL)),
    CONSTRAINT "permission_audit_events_scope_check" CHECK (("scope" IS NULL AND "scope_guild_id" IS NULL AND "scope_guild_discord_id" IS NULL) OR ("scope" = 'platform' AND "scope_guild_id" IS NULL AND "scope_guild_discord_id" IS NULL) OR ("scope" = 'discord-guild' AND "scope_guild_id" IS NOT NULL AND "scope_guild_discord_id" IS NOT NULL)),
    CONSTRAINT "permission_audit_events_permission_check" CHECK (("permission_definition_id" IS NULL AND "permission_key" IS NULL) OR ("permission_definition_id" IS NOT NULL AND "permission_key" ~ '^[a-z][a-z0-9]*(\.[a-z][a-z0-9]*)+$')),
    CONSTRAINT "permission_audit_events_reason_check" CHECK ("reason" IS NULL OR length(btrim("reason")) > 0)
);

CREATE TABLE "permission_catalog_state" (
    "id" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "checksum" TEXT NOT NULL,
    "synced_at" TIMESTAMPTZ(3) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    CONSTRAINT "permission_catalog_state_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "permission_catalog_state_singleton_check" CHECK ("id" = 'compiled-permission-catalog'),
    CONSTRAINT "permission_catalog_state_version_check" CHECK (length(btrim("version")) > 0),
    CONSTRAINT "permission_catalog_state_checksum_check" CHECK ("checksum" ~ '^sha256:[0-9a-f]{64}$')
);

CREATE UNIQUE INDEX "guild_discord_guild_id_key" ON "guilds"("discord_guild_id");
CREATE INDEX "permission_principals_guild_enabled_idx" ON "permission_principals"("guild_id", "enabled");
CREATE UNIQUE INDEX "permission_principals_identity_key" ON "permission_principals"("type", "guild_id", "external_id");
CREATE UNIQUE INDEX "permission_definitions_key_key" ON "permission_definitions"("key");
CREATE INDEX "permission_definitions_enabled_idx" ON "permission_definitions"("enabled");
CREATE INDEX "permission_assignments_lookup_idx" ON "permission_assignments"("principal_id", "scope", "guild_id", "enabled");
CREATE INDEX "permission_assignments_permission_idx" ON "permission_assignments"("permission_definition_id");
CREATE INDEX "permission_assignments_guild_idx" ON "permission_assignments"("guild_id");
CREATE UNIQUE INDEX "permission_assignments_active_platform_key" ON "permission_assignments"("principal_id", "permission_definition_id", "effect") WHERE "scope" = 'platform' AND "enabled" AND "revoked_at" IS NULL;
CREATE UNIQUE INDEX "permission_assignments_active_guild_key" ON "permission_assignments"("principal_id", "permission_definition_id", "effect", "guild_id") WHERE "scope" = 'discord-guild' AND "enabled" AND "revoked_at" IS NULL;
CREATE INDEX "permission_audit_events_correlation_idx" ON "permission_audit_events"("correlation_id");
CREATE INDEX "permission_audit_events_assignment_idx" ON "permission_audit_events"("assignment_id");
CREATE INDEX "permission_audit_events_scope_time_idx" ON "permission_audit_events"("scope", "scope_guild_id", "occurred_at");
CREATE INDEX "permission_audit_events_actor_idx" ON "permission_audit_events"("actor_principal_id");
CREATE INDEX "permission_audit_events_target_idx" ON "permission_audit_events"("target_principal_id");
CREATE INDEX "permission_audit_events_permission_idx" ON "permission_audit_events"("permission_definition_id");

ALTER TABLE "permission_principals" ADD CONSTRAINT "permission_principals_guild_id_fkey" FOREIGN KEY ("guild_id") REFERENCES "guilds"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "permission_assignments" ADD CONSTRAINT "permission_assignments_principal_id_fkey" FOREIGN KEY ("principal_id") REFERENCES "permission_principals"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "permission_assignments" ADD CONSTRAINT "permission_assignments_permission_definition_id_fkey" FOREIGN KEY ("permission_definition_id") REFERENCES "permission_definitions"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "permission_assignments" ADD CONSTRAINT "permission_assignments_guild_id_fkey" FOREIGN KEY ("guild_id") REFERENCES "guilds"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "permission_audit_events" ADD CONSTRAINT "permission_audit_events_actor_principal_id_fkey" FOREIGN KEY ("actor_principal_id") REFERENCES "permission_principals"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "permission_audit_events" ADD CONSTRAINT "permission_audit_events_target_principal_id_fkey" FOREIGN KEY ("target_principal_id") REFERENCES "permission_principals"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "permission_audit_events" ADD CONSTRAINT "permission_audit_events_scope_guild_id_fkey" FOREIGN KEY ("scope_guild_id") REFERENCES "guilds"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "permission_audit_events" ADD CONSTRAINT "permission_audit_events_permission_definition_id_fkey" FOREIGN KEY ("permission_definition_id") REFERENCES "permission_definitions"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "permission_audit_events" ADD CONSTRAINT "permission_audit_events_assignment_id_fkey" FOREIGN KEY ("assignment_id") REFERENCES "permission_assignments"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE FUNCTION enforce_permission_assignment_guild() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE principal_guild_id UUID;
BEGIN
    SELECT "guild_id" INTO principal_guild_id FROM "permission_principals" WHERE "id" = NEW."principal_id";
    IF NEW."scope" = 'discord-guild' AND NEW."guild_id" IS DISTINCT FROM principal_guild_id THEN
        RAISE EXCEPTION 'Discord-guild assignment must use the principal guild' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER "permission_assignments_guild_guard" BEFORE INSERT OR UPDATE ON "permission_assignments" FOR EACH ROW EXECUTE FUNCTION enforce_permission_assignment_guild();

CREATE FUNCTION prevent_created_at_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW."created_at" IS DISTINCT FROM OLD."created_at" THEN
        RAISE EXCEPTION 'created_at is immutable' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER "guilds_created_at_immutable" BEFORE UPDATE ON "guilds" FOR EACH ROW EXECUTE FUNCTION prevent_created_at_change();
CREATE TRIGGER "permission_principals_created_at_immutable" BEFORE UPDATE ON "permission_principals" FOR EACH ROW EXECUTE FUNCTION prevent_created_at_change();
CREATE TRIGGER "permission_definitions_created_at_immutable" BEFORE UPDATE ON "permission_definitions" FOR EACH ROW EXECUTE FUNCTION prevent_created_at_change();
CREATE TRIGGER "permission_assignments_created_at_immutable" BEFORE UPDATE ON "permission_assignments" FOR EACH ROW EXECUTE FUNCTION prevent_created_at_change();
CREATE TRIGGER "permission_catalog_state_created_at_immutable" BEFORE UPDATE ON "permission_catalog_state" FOR EACH ROW EXECUTE FUNCTION prevent_created_at_change();

CREATE FUNCTION reject_permission_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'permission audit events are append-only' USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER "permission_audit_events_append_only" BEFORE UPDATE OR DELETE ON "permission_audit_events" FOR EACH ROW EXECUTE FUNCTION reject_permission_audit_mutation();
