import { AuthenticationDomainError } from "./errors.js";

declare const identifierBrand: unique symbol;

type BrandedIdentifier<TName extends string> = string & {
  readonly [identifierBrand]: TName;
};

/** Immutable internal identifier for a canonical human platform account. */
export type PlatformUserId = BrandedIdentifier<"PlatformUserId">;
/** Immutable internal identifier for a linked provider identity. */
export type ExternalIdentityId = BrandedIdentifier<"ExternalIdentityId">;
/** Immutable internal identifier for a persisted browser session record. */
export type BrowserSessionId = BrandedIdentifier<"BrowserSessionId">;
/** Immutable internal identifier for a one-time OAuth transaction. */
export type OAuthTransactionId = BrandedIdentifier<"OAuthTransactionId">;
/** Immutable internal identifier for an encrypted OAuth credential record. */
export type OAuthCredentialId = BrandedIdentifier<"OAuthCredentialId">;
/** Immutable internal identifier for a Discord guild-membership snapshot. */
export type DiscordGuildMembershipId =
  BrandedIdentifier<"DiscordGuildMembershipId">;
/** Immutable internal identifier for an append-only authentication audit event. */
export type AuthenticationAuditEventId =
  BrandedIdentifier<"AuthenticationAuditEventId">;
/** Reserved internal identifier for a future non-human workload identity. */
export type ServiceIdentityId = BrandedIdentifier<"ServiceIdentityId">;
/** Immutable internal identifier for an existing persisted guild record. */
export type GuildId = BrandedIdentifier<"GuildId">;
/** Verified immutable Discord user snowflake supplied by a trusted provider. */
export type DiscordUserId = BrandedIdentifier<"DiscordUserId">;
/** Verified immutable Discord guild snowflake supplied by trusted composition. */
export type DiscordGuildId = BrandedIdentifier<"DiscordGuildId">;
/** Verified immutable Discord role snowflake supplied by trusted Discord data. */
export type DiscordRoleId = BrandedIdentifier<"DiscordRoleId">;
/** Canonical UUID used to correlate one operation across transport and audit. */
export type AuthenticationCorrelationId =
  BrandedIdentifier<"AuthenticationCorrelationId">;
/** Canonical request UUID generated by the trusted HTTP transport. */
export type AuthenticationRequestId =
  BrandedIdentifier<"AuthenticationRequestId">;
/** Keyed-HMAC digest encoded as exactly 32 lowercase hexadecimal bytes. */
export type AuthenticationDigest = BrandedIdentifier<"AuthenticationDigest">;
/** Ephemeral opaque secret that must never be written to persistence or logs. */
export type OpaqueAuthenticationSecret =
  BrandedIdentifier<"OpaqueAuthenticationSecret">;

const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const DISCORD_SNOWFLAKE_PATTERN = /^[1-9][0-9]{16,19}$/;
const DIGEST_PATTERN = /^[0-9a-f]{64}$/;

/** Validates and brands a platform-user UUID at an untrusted boundary. */
export function platformUserId(value: string): PlatformUserId {
  return canonicalUuid(value, "platform user") as PlatformUserId;
}

/** Validates and brands an external-identity UUID at an untrusted boundary. */
export function externalIdentityId(value: string): ExternalIdentityId {
  return canonicalUuid(value, "external identity") as ExternalIdentityId;
}

/** Validates and brands a browser-session UUID at an untrusted boundary. */
export function browserSessionId(value: string): BrowserSessionId {
  return canonicalUuid(value, "browser session") as BrowserSessionId;
}

/** Validates and brands an OAuth-transaction UUID at an untrusted boundary. */
export function oauthTransactionId(value: string): OAuthTransactionId {
  return canonicalUuid(value, "OAuth transaction") as OAuthTransactionId;
}

/** Validates and brands an OAuth-credential UUID at an untrusted boundary. */
export function oauthCredentialId(value: string): OAuthCredentialId {
  return canonicalUuid(value, "OAuth credential") as OAuthCredentialId;
}

/** Validates and brands a Discord membership UUID at an untrusted boundary. */
export function discordGuildMembershipId(
  value: string,
): DiscordGuildMembershipId {
  return canonicalUuid(value, "Discord guild membership") as DiscordGuildMembershipId;
}

/** Validates and brands an authentication-audit UUID at an untrusted boundary. */
export function authenticationAuditEventId(
  value: string,
): AuthenticationAuditEventId {
  return canonicalUuid(value, "authentication audit event") as AuthenticationAuditEventId;
}

/** Validates and brands a future service-identity UUID. */
export function serviceIdentityId(value: string): ServiceIdentityId {
  return canonicalUuid(value, "service identity") as ServiceIdentityId;
}

/** Validates and brands an internal guild UUID. */
export function guildId(value: string): GuildId {
  return canonicalUuid(value, "guild") as GuildId;
}

/** Validates and brands a canonical operation correlation UUID. */
export function authenticationCorrelationId(
  value: string,
): AuthenticationCorrelationId {
  return canonicalUuid(value, "correlation") as AuthenticationCorrelationId;
}

/** Validates and brands a trusted request UUID. */
export function authenticationRequestId(
  value: string,
): AuthenticationRequestId {
  return canonicalUuid(value, "request") as AuthenticationRequestId;
}

/** Validates and brands a Discord user snowflake. */
export function discordUserId(value: string): DiscordUserId {
  return discordSnowflake(value, "Discord user") as DiscordUserId;
}

/** Validates and brands a Discord guild snowflake. */
export function discordGuildId(value: string): DiscordGuildId {
  return discordSnowflake(value, "Discord guild") as DiscordGuildId;
}

/** Validates and brands a Discord role snowflake. */
export function discordRoleId(value: string): DiscordRoleId {
  return discordSnowflake(value, "Discord role") as DiscordRoleId;
}

/** Validates a lowercase 32-byte keyed-HMAC digest for safe persistence. */
export function authenticationDigest(value: string): AuthenticationDigest {
  if (!DIGEST_PATTERN.test(value))
    throw new AuthenticationDomainError(
      "invalid-identifier",
      "Authentication digests must be 64 lowercase hexadecimal characters.",
    );
  return value as AuthenticationDigest;
}

/** Brands an in-memory opaque secret after rejecting empty or control-filled values. */
export function opaqueAuthenticationSecret(
  value: string,
): OpaqueAuthenticationSecret {
  if (value.length < 32 || value.length > 4096 || /[\u0000-\u001f\u007f]/.test(value))
    throw new AuthenticationDomainError(
      "invalid-identifier",
      "Opaque authentication secrets must have a safe bounded representation.",
    );
  return value as OpaqueAuthenticationSecret;
}

function canonicalUuid(value: string, label: string): string {
  if (!UUID_PATTERN.test(value))
    throw new AuthenticationDomainError(
      "invalid-identifier",
      `${label} identifiers must be canonical lowercase UUIDs.`,
    );
  return value;
}

function discordSnowflake(value: string, label: string): string {
  if (!DISCORD_SNOWFLAKE_PATTERN.test(value))
    throw new AuthenticationDomainError(
      "invalid-identifier",
      `${label} identifiers must be 17 to 20 digit Discord snowflakes.`,
    );
  return value;
}
